sudu: required

language: generic

services: -docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t coby5502/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true coby5502/docker-react-app npm run test -- --coverage

deploy:
  provider: eleasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-477404879761"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
